version: "3.7"
services:
  app:
    container_name: laravel
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: "laravelapp"
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_DATABASE: "balloonsim"
      MARIADB_USER: "root"
      MARIADB_PASSWORD: "root"
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: ebspace/armhf-phpmyadmin
    domainname: localhost
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: "mariadb"
    ports:
      - "80:80"
    depends_on:
      - mariadb
